### ISSUE TITLE
Detect subprocess crashes

### ISSUE THREAD

**Issue by osnr** [FolkComputer/folk#110]
Often the display/camera/whatever just segfaults and there's no way of knowing that it went wrong / why there's nothing displaying. Could also try to auto-restart (Erlang)

**Comment by nickdex** [comment]
I think I'm facing this issue. 
It keeps restarting.

Started folk.service - Folk service.
Oct 26 01:05:06 folk-nikhil make[219919]: make: Entering directory '/home/folk/folk'
Oct 26 01:05:06 folk-nikhil make[219919]: tclsh8.6 main.tcl
Oct 26 01:05:08 folk-nikhil make[219925]: Failed to load calibration poses: couldn't open "/home/folk/folk-live/folk-calibration-poses.txt": no such file or directory
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> virtual-programs/apriltags.folk-m57:0-1
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create virtual-programs/apriltags.folk-m57:0-1 -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> virtual-programs/apriltags.folk-m57:0-2
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create virtual-programs/apriltags.folk-m57:0-2 -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> watchdog
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create watchdog -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Warning: Unable to generate getter for `VTerminal tmt`: Unrecognized rtype TMT
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> display
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create display -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.0-event-kbd
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.0-event-kbd -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.0-event-kbd
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.0-event-kbd -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.3-event-kbd
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.3-event-kbd -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.3-event-kbd
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.3-event-kbd -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> camera /dev/video0 width 1280 height 720
Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create camera /dev/video0 width 1280 height 720 -> folk-nikhil
Oct 26 01:05:09 folk-nikhil make[220278]: Display pid: 220278
Oct 26 01:05:09 folk-nikhil make[220280]: Error child process exited abnormally
Oct 26 01:05:09 folk-nikhil make[220282]: Error child process exited abnormally
Oct 26 01:05:09 folk-nikhil make[220284]: Error child process exited abnormally
Oct 26 01:05:09 folk-nikhil make[220288]: Error child process exited abnormally
Oct 26 01:05:09 folk-nikhil make[220302]: the driver changed the time per frame from 60/1 to 1/60
Oct 26 01:05:10 folk-nikhil make[220302]: camera-usb: /dev/video0 (width 1280 height 720) (tid 220302) booted at 1729904710195
Oct 26 01:05:10 folk-nikhil make[220278]: Gpu: No displays found
Oct 26 01:05:10 folk-nikhil make[220278]: Gpu: Found 1 Vulkan devices
Oct 26 01:05:10 folk-nikhil make[220278]: Gpu: Found 0 displays
Oct 26 01:05:10 folk-nikhil make[220277]: process: Subprocess 'display' (220278) died!
Oct 26 01:05:10 folk-nikhil sudo[220385]:     folk : PWD=/home/folk/folk ; USER=root ; COMMAND=/usr/bin/systemctl restart folk
Oct 26 01:05:10 folk-nikhil sudo[220385]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Oct 26 01:05:10 folk-nikhil sudo[220385]: pam_unix(sudo:session): session closed for user root
Oct 26 01:05:10 folk-nikhil systemd[1]: Stopping folk.service - Folk service...
Oct 26 01:05:10 folk-nikhil make[219919]: make: *** [Makefile:2: start] Terminated
Oct 26 01:05:10 folk-nikhil systemd[1]: folk.service: Deactivated successfully.
Oct 26 01:05:10 folk-nikhil systemd[1]: Stopped folk.service - Folk service.
Oct 26 01:05:10 folk-nikhil systemd[1]: folk.service: Consumed 6.887s CPU time.
Oct 26 01:05:10 folk-nikhil systemd[1]: Started folk.service - Folk service.
Oct 26 01:05:10 folk-nikhil make[220388]: make: Entering directory '/home/folk/folk'
Oct 26 01:05:10 folk-nikhil make[220388]: tclsh8.6 main.tcl

**Comment by osnr** [comment]
> I think I'm facing this issue. It keeps restarting.
> 
> Started folk.service - Folk service. Oct 26 01:05:06 folk-nikhil make[219919]: make: Entering directory '/home/folk/folk' Oct 26 01:05:06 folk-nikhil make[219919]: tclsh8.6 main.tcl Oct 26 01:05:08 folk-nikhil make[219925]: Failed to load calibration poses: couldn't open "/home/folk/folk-live/folk-calibration-poses.txt": no such file or directory Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> virtual-programs/apriltags.folk-m57:0-1 Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create virtual-programs/apriltags.folk-m57:0-1 -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> virtual-programs/apriltags.folk-m57:0-2 Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create virtual-programs/apriltags.folk-m57:0-2 -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> watchdog Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create watchdog -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Warning: Unable to generate getter for `VTerminal tmt`: Unrecognized rtype TMT Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> display Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create display -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.0-event-kbd Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.0-event-kbd -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.0-event-kbd Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.0-event-kbd -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.3-event-kbd Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.3-event-kbd -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.3-event-kbd Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create keyboard-/dev/input/by-path/pci-0000:00:14.0-usbv2-0:9:1.3-event-kbd -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create folk-nikhil -> camera /dev/video0 width 1280 height 720 Oct 26 01:05:09 folk-nikhil make[219925]: Mailbox create camera /dev/video0 width 1280 height 720 -> folk-nikhil Oct 26 01:05:09 folk-nikhil make[220278]: Display pid: 220278 Oct 26 01:05:09 folk-nikhil make[220280]: Error child process exited abnormally Oct 26 01:05:09 folk-nikhil make[220282]: Error child process exited abnormally Oct 26 01:05:09 folk-nikhil make[220284]: Error child process exited abnormally Oct 26 01:05:09 folk-nikhil make[220288]: Error child process exited abnormally Oct 26 01:05:09 folk-nikhil make[220302]: the driver changed the time per frame from 60/1 to 1/60 Oct 26 01:05:10 folk-nikhil make[220302]: camera-usb: /dev/video0 (width 1280 height 720) (tid 220302) booted at 1729904710195 Oct 26 01:05:10 folk-nikhil make[220278]: Gpu: No displays found Oct 26 01:05:10 folk-nikhil make[220278]: Gpu: Found 1 Vulkan devices Oct 26 01:05:10 folk-nikhil make[220278]: Gpu: Found 0 displays Oct 26 01:05:10 folk-nikhil make[220277]: process: Subprocess 'display' (220278) died! Oct 26 01:05:10 folk-nikhil sudo[220385]: folk : PWD=/home/folk/folk ; USER=root ; COMMAND=/usr/bin/systemctl restart folk Oct 26 01:05:10 folk-nikhil sudo[220385]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001) Oct 26 01:05:10 folk-nikhil sudo[220385]: pam_unix(sudo:session): session closed for user root Oct 26 01:05:10 folk-nikhil systemd[1]: Stopping folk.service - Folk service... Oct 26 01:05:10 folk-nikhil make[219919]: make: *** [Makefile:2: start] Terminated Oct 26 01:05:10 folk-nikhil systemd[1]: folk.service: Deactivated successfully. Oct 26 01:05:10 folk-nikhil systemd[1]: Stopped folk.service - Folk service. Oct 26 01:05:10 folk-nikhil systemd[1]: folk.service: Consumed 6.887s CPU time. Oct 26 01:05:10 folk-nikhil systemd[1]: Started folk.service - Folk service. Oct 26 01:05:10 folk-nikhil make[220388]: make: Entering directory '/home/folk/folk' Oct 26 01:05:10 folk-nikhil make[220388]: tclsh8.6 main.tcl

Do you have a display plugged into your Folk machine?

**Comment by osnr** [comment]
Fixed in ccc6af0eccfa8eb789afaab4d5ff7f4ef9d17a75
