### ISSUE TITLE
Ctrl-Esc to stop folk systemd service

### ISSUE THREAD

**Issue by osnr** [FolkComputer/folk#172]
so you don't have to race its restart to set up wifi from terminal or whatever

related to #170 ?

**Comment by cwervo** [comment]
Hmm, should we have one shortcut for stopping and one for restarting? I feel like both are good for different situations and useful to have access to basically all the time.

How about:
- `Shift + Esc` to stop the daemon
- `Control + Esc` stays mapped to restarting the current Folk process

**Comment by cwervo** [comment]
Oh you’re right, my bad, it’s currently Alt
