### ISSUE TITLE
Can't calibrate (anymore) 

### ISSUE THREAD

**Issue by breezahbu** [FolkComputer/folk#178]
seems to have happened out of the sudden. Not sure if something in the system was changed. Calibration page shows up, but after clicking on the "Start-calibrate" but no further output. Some pages load, but /new and  /calibrate seem only to work partly. 

journalctl -u folk -f

Okt 29 21:02:42 bwow make[3062]: key "protocols" not known in dictionary
Okt 29 21:02:42 bwow make[3062]:     while executing
Okt 29 21:02:42 bwow make[3062]: "dict get $res protocols"
Okt 29 21:02:42 bwow make[3062]:     (procedure "::websocket::test" line 19)
Okt 29 21:02:42 bwow make[3062]:     invoked from within
Okt 29 21:02:42 bwow make[3062]: "::websocket::test $::serverSock $chan "/ws" $headers"
Okt 29 21:02:42 bwow make[3062]:     (procedure "handleRead" line 58)
Okt 29 21:02:42 bwow make[3062]:     invoked from within

**Comment by osnr** [comment]
Hello -- did it previously work on the same system? Have you installed the `tcllib` package at some point? (that package may break Folk)

**Comment by breezahbu** [comment]
It did and I did. "apt-cache remove tcllib" did the trick. Not sure, but that may have been installed for troubleshooting purposes. Many thanks, now I can continue with one of the most fun and inspiring systems I have seen for a long time. Thanks for that too.
